# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Actions Example

on:
  pull_request:
  push:
    branches: 
      - master
      - develop
jobs:
  test:
    name: Running Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install npm
      run: npm install
    - name: Build the project
      run: npm run build --if-present
    - name: Run the unit tests      
      run: npm test
